### PR TITLE
Fixes @prefix counting (in case of 0) & adds new cmd 'nssort' & minor things

### PR DESCRIPTION
**Pull request by hoijui**

### CODE REVIEW

**Comment by seebi** [comment]
Hi @elevont --- running your new command results in an error - can you fix this?

```
∴ rdf nssort
/Users/seebi/.local/bin/rdf: line 1048: prefixfile: unbound variable
```

**Comment by hoijui** [comment]
thank you @seebi !
should be fixed now.
(I before only tested the commands in the shell directly, instead of within the script, sorry :/ )

**Comment by seebi** [comment]
@hoijui Given this file

```
@prefix : <https://sebastian.tramp.name/>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

: a foaf:Person .

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
```

I get this error:

```
∴ rdf nssort index.ttl
head: illegal line count -- -1
```

Any idea?

**Comment by hoijui** [comment]
Thanks for the  testing! :-)
Apparently I was using `head` in a way that works on Linux but not on Mac.
It should now be fixed.

**Comment by hoijui** [comment]
Superseded by #24 and #25

**Pull request closed without merging**
